Added Site Migrate Option

diff --git a/usr/local/sbin/easyengine b/usr/local/sbin/easyengine
--- a/usr/local/sbin/easyengine
+++ b/usr/local/sbin/easyengine
@@ -5,6 +5,7 @@
 # Make Variables Available For Later Use
 LOGDIR=/var/log/easyengine
 ERRORLOG=/var/log/easyengine/error.log
+MIGRATELOG=/var/log/easyengine/rsync.log
 
 # Check Auto Assume Yes Or No To Apt-Get
 grep apt-get-assume-yes /etc/easyengine/ee.conf | grep -i true &>> /dev/null
@@ -20,6 +21,13 @@ fi
 OwnError()
 {
 	echo -e "[ `date` ] \033[31m $@ \e[0m" | tee -ai $ERRORLOG
+	exit 101
+}
+
+# Capture Sync Errors
+SyncError()
+{
+	echo -e "[ `date` ] \033[31m $@ \e[0m" | tee -ai $MIGRATELOG
 	exit 101
 }
 
@@ -730,7 +738,128 @@ REMOVENGINXCONF()
 }
 
 
+EEMIGRATE()
+{
+	if [ ! -f $MIGRATELOG ]
+	then
+		sudo touch $MIGRATELOG
+		sudo chmod 666 $MIGRATELOG
+	fi
 
+	# Souce Domain
+	read -p " Enter Source Domain Name To rsync: " DOMAIN
+
+	# Ask for MySQL Dump (If Option is Not "y", it will sync only webroot)
+	read -p " Do you want to Dump MySQL (y/n) [y]: " NODATABASE
+
+	# If Enter Is Pressed, Then Dump MySQL = y
+	if [[ $NODATABASE = "" ]]
+	then
+		NODATABASE=y
+	fi
+
+	if [ "$NODATABASE" == "y" ]
+	then
+		# MySQL Informatiom
+		WPDBNAME=$(grep DB_NAME /var/www/$DOMAIN/wp-config.php | cut -d"'" -f4)
+		MYSQLUSER=$(grep DB_USER /var/www/$DOMAIN/wp-config.php | cut -d"'" -f4)
+		MYSQLPASS=$(grep DB_PASS /var/www/$DOMAIN/wp-config.php | cut -d"'" -f4)
+
+		echo -e "\n `date` \n" &>> $MIGRATELOG
+		echo -e " DOMAIN = $DOMAIN \n WPDBNAME = $WPDBNAME \n MYSQLUSER = $MYSQLUSER \n MYSQLPASS = $MYSQLPASS" | tee -ai $MIGRATELOG
+
+		echo -e "\033[34m Taking MySQL Dump, Please Wait...  \e[0m"
+		mkdir -p /var/www/$DOMAIN/backup
+		rm -rf /var/www/$DOMAIN/backup/$WPDBNAME.sql
+		mysqldump --max_allowed_packet=512M -u $MYSQLUSER -p$MYSQLPASS $WPDBNAME > /var/www/$DOMAIN/backup/$WPDBNAME.sql || SyncError "Unable To Dump MySQL For $WPDBNAME"	
+
+	fi
+
+	# Destination Domain
+	echo
+	echo -e " Required Destination Server Details: "
+	read -p " Enter Usernames [www-data]: " DESTUSER
+	read -p " Enter Destination IP: " DESTIP
+	read -p " Enter Destination PORT [22]: " DESTPORT
+	read -p " Enter Destination Domain Name To rsync: " DESTDOMAIN
+	echo
+
+	# If Enter Is Pressed, Then Destination User = www-data
+	if [[ $DESTUSER = "" ]]
+	then
+		DESTUSER=www-data
+	fi
+
+	# If Enter Is Pressed, Then Destination Port = 22
+	if [[ $DESTPORT = "" ]]
+	then
+		DESTPORT=22
+	fi
+
+	# Ignore Database
+	if [ "$NODATABASE" == "y" ]
+	then
+		# Lets Import MySQL
+		echo -e "\033[34m Fetching Destination DB Name, DB User & DB Password...  \e[0m"
+		rsync -avzh $DESTUSER@$DESTIP:/var/www/$DESTDOMAIN/wp-config.php /tmp/ || SyncError "Unable To Fetch wp-config.php From $DESTDOMAIN"
+
+		# Rename wp-config file name to avoid conflict
+		mv /tmp/wp-config.php /tmp/$DESTDOMAIN-wp-config.php
+
+		# Get Destination Database Name, Username and Password
+		DESTDBNAME=$(grep DB_NAME /tmp/$DESTDOMAIN-wp-config.php | cut -d"'" -f4)
+		DESTDBUSER=$(grep DB_USER /tmp/$DESTDOMAIN-wp-config.php | cut -d"'" -f4)
+		DESTDBPASS=$(grep DB_PASS /tmp/$DESTDOMAIN-wp-config.php | cut -d"'" -f4)
+		echo -e " DESTIP = $DESTIP \n DESTDBNAME = $DESTDBNAME \n DESTDBUSER = $DESTDBUSER \n DESTDBPASS = $DESTDBPASS" | tee -ai $MIGRATELOG
+	fi
+
+	read -p " Are You Sure To rsync $DOMAIN To $DESTDOMAIN (y/n): " ANSWER
+
+	if [ "$ANSWER" == "y" ]
+	then
+		echo -e "\033[34m Sync $DOMAIN To $DESTDOMAIN, Please Wait...  \e[0m"
+		
+		if [ "$NODATABASE" == "y" ]
+		then
+			# Ask for Exclude Upload Directory
+			read -p " Do You Want To Exclude Upload Directory (y/n): " EXCLUDEDIR
+			if [ "$EXCLUDEDIR" == "y" ]
+			then
+				rsync -avzh --exclude="wp-content/uploads/"  /var/www/$DOMAIN/htdocs /var/www/$DOMAIN/backup/$WPDBNAME.sql $DESTUSER@$DESTIP:/var/www/$DESTDOMAIN/ || SyncError "Unable To Sync $DOMAIN To $DESTDOMAIN"
+			else
+				rsync -avzh /var/www/$DOMAIN/htdocs /var/www/$DOMAIN/backup/$WPDBNAME.sql $DESTUSER@$DESTIP:/var/www/$DESTDOMAIN/ || SyncError "Unable To Sync $DOMAIN To $DESTDOMAIN"
+			fi
+
+			# Ask for Import Database from Source to Destination
+			read -p " Do You Want to Import MySQL Database from $DOMAIN to $DESTDOMAIN (y/n): " DBIMPORT
+			if [ "$DBIMPORT" == "y" ]
+			then
+				echo -e "\033[34m Importing MySQL, Please Wait...  \e[0m"
+				ssh $DESTUSER@$DESTIP -p $DESTPORT "mysql -u $DESTDBUSER -p$DESTDBPASS $DESTDBNAME < /var/www/$DESTDOMAIN/$WPDBNAME.sql" || SyncError "Unable To Import MySQL On $DESTDOMAIN"
+			else
+				echo -e "\033[31m User Denied to Import Database from $DOMAIN to $DESTDOMAIN \n \e[0m" | tee -ai $MIGRATELOG
+			fi
+		else
+			rsync -avzh /var/www/$DOMAIN/htdocs $DESTUSER@$DESTIP:/var/www/$DESTDOMAIN/ || SyncError "Unable To Sync $DOMAIN To $DESTDOMAIN"
+		fi
+
+		if [ "$NODATABASE" == "y" ]
+		then
+			# Remove Config file from /tmp/ Directory and Database backup file from Destination
+			rm -f /tmp/$DESTDOMAIN-wp-config.php
+			ssh $DESTUSER@$DESTIP -p $DESTPORT "rm -f /var/www/$DESTDOMAIN/$WPDBNAME.sql" || SyncError "Unable To Remove MySQL Backup File $WPDBNAME.sql"
+
+			# Display Important Information After Completing rsync Process
+			echo -e "\033[34m For The First Time rsync, Add Following Lines To /var/www/$DESTDOMAIN/wp-config.php  \e[0m"
+			echo -e "\033[1;33m \n define( 'WP_HOME', 'http://$DESTDOMAIN/' ); \n define( 'WP_SITEURL', 'http://$DESTDOMAIN/' ); \n \e[0m"
+			echo -e "IMPORTANT: Don't Forget To Use Search & Replace Plugin"
+		fi
+	else
+		# User Denied Messages
+		echo
+		echo -e "\033[31m User Denied rsync from $DOMAIN to $DESTDOMAIN \e[0m" | tee -ai $MIGRATELOG
+	fi
+}
 
 
 # Easy Engine System Settings
@@ -1636,6 +1765,10 @@ then
 
 		fi
 
+	elif [ "$2" = "migrate" ]
+	then
+		# Call EEMIGRATE Function
+		EEMIGRATE
 
 	#elif [ "$2" = "delete" ]
 	#then
